# Data cleaning 🧹

The process of fixing/ removing: incomplete, incorrect, or irrelevant (không liên quan) data.

~75% of work done with Pandas is data cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./pokemon.csv")

df

      No        Name   Type 1  Type 2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

## Drop irrelevant columns

In [3]:
# 1. Drop irrelevant columns
df = df.drop(columns=["Legendary", "No"])

In [4]:
df

           Name   Type 1  Type 2  Height  Weight
0     Bulbasaur    Grass  Poison     0.7     6.9
1       Ivysaur    Grass  Poison     1.0    13.0
2      Venusaur    Grass  Poison     2.0   100.0
3    Charmander     Fire     NaN     0.6     8.5
4    Charmeleon     Fire     NaN     1.1    19.0
..          ...      ...     ...     ...     ...
145     Moltres     Fire  Flying     2.0    60.0
146     Dratini   Dragon     NaN     1.8     3.3
147   Dragonair   Dragon     NaN     4.0    16.5
148   Dragonite   Dragon  Flying     2.2   210.0
149      Mewtwo  Psychic     NaN     2.0   122.0

[150 rows x 5 columns]

## Handle missing data

In [5]:
# df = df.dropna(subset=["Type 2"]) # dropna là viết tắc của drop not available
df = df.fillna({"Type 2": "None"})

In [6]:
df

           Name   Type 1  Type 2  Height  Weight
0     Bulbasaur    Grass  Poison     0.7     6.9
1       Ivysaur    Grass  Poison     1.0    13.0
2      Venusaur    Grass  Poison     2.0   100.0
3    Charmander     Fire    None     0.6     8.5
4    Charmeleon     Fire    None     1.1    19.0
..          ...      ...     ...     ...     ...
145     Moltres     Fire  Flying     2.0    60.0
146     Dratini   Dragon    None     1.8     3.3
147   Dragonair   Dragon    None     4.0    16.5
148   Dragonite   Dragon  Flying     2.2   210.0
149      Mewtwo  Psychic    None     2.0   122.0

[150 rows x 5 columns]

## Fix inconsistent values

In [7]:
df["Type 1"] = df["Type 1"].replace({"Grass": "GRASS"})

In [8]:
df

           Name   Type 1  Type 2  Height  Weight
0     Bulbasaur    GRASS  Poison     0.7     6.9
1       Ivysaur    GRASS  Poison     1.0    13.0
2      Venusaur    GRASS  Poison     2.0   100.0
3    Charmander     Fire    None     0.6     8.5
4    Charmeleon     Fire    None     1.1    19.0
..          ...      ...     ...     ...     ...
145     Moltres     Fire  Flying     2.0    60.0
146     Dratini   Dragon    None     1.8     3.3
147   Dragonair   Dragon    None     4.0    16.5
148   Dragonite   Dragon  Flying     2.2   210.0
149      Mewtwo  Psychic    None     2.0   122.0

[150 rows x 5 columns]