In [2]:
import pandas as pd
df = pd.read_csv('../test.csv')

In [3]:
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

### 1 Grouping

In [4]:
# groupby() : nhóm dữ liệu theo 1 cột hoặc nhiều cột
df.groupby('Age').Age.count() # giống df['Age'].value_counts()

Age
18.00    2614
19.00    1731
20.00    2335
21.00    1930
22.00    1417
23.00    1870
24.00    2296
25.00    1953
26.00    1362
27.00    1719
28.00    2292
29.00    2152
30.00    1361
31.00    1660
32.00    1227
32.08       1
33.00    2057
34.00    1785
35.00    1940
36.00    1742
37.00    1789
38.00    3008
39.00    2279
40.00    1950
41.00    2093
42.00    2295
43.00    2506
44.00    2242
45.00    2329
46.00    2728
47.00    2740
48.00    2459
49.00    3425
50.00    2311
51.00    2544
52.00    1687
53.00    2958
54.00    2549
55.00    1923
56.00    3432
57.00    2875
58.00    1982
59.00    2551
60.00    1701
Name: Age, dtype: int64

In [5]:
df.groupby('Work/Study Hours')['Work/Study Hours'].min()

Work/Study Hours
0.0      0.0
1.0      1.0
2.0      2.0
3.0      3.0
4.0      4.0
5.0      5.0
6.0      6.0
7.0      7.0
8.0      8.0
9.0      9.0
10.0    10.0
11.0    11.0
12.0    12.0
Name: Work/Study Hours, dtype: float64

In [6]:
df.groupby('id').apply(lambda df: df['Profession'].iloc[0])

C:\Users\hoang\AppData\Local\Temp\ipykernel_10164\4092399102.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('id').apply(lambda df: df['Profession'].iloc[0])

id
140700                     Judge
140701    Educational Consultant
140702                   Teacher
140703                       NaN
140704                   Teacher
                   ...
234495                     Pilot
234496                     Pilot
234497                       NaN
234498         Marketing Manager
234499    Educational Consultant
Length: 93800, dtype: object

In [7]:
df.groupby(['Age', 'Profession']).apply(lambda df: df.loc[df.Age.idxmax()]) # lấy dòng có tuổi lớn nhất trong mỗi nhóm

C:\Users\hoang\AppData\Local\Temp\ipykernel_10164\338590452.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(['Age', 'Profession']).apply(lambda df: df.loc[df.Age.idxmax()]) # lấy dòng có tuổi lớn nhất trong mỗi nhóm

                                 id         Name  Gender   Age       City  \
Age  Profession
18.0 Content Writer          197562         Vani  Female  18.0     Indore
     Educational Consultant  197564        Kiran    Male  18.0     Meerut
     Entrepreneur            183051       Vrinda  Female  18.0     Meerut
     Financial Analyst       189494         Diya  Female  18.0    Kolkata
     Manager                 206064        Vidhi  Female  18.0   Ludhiana
...                             ...          ...     ...   ...        ...
60.0 Sales Executive         142141       Anjali  Female  60.0  Bangalore
     Software Engineer       145917  Raghavendra    Male  60.0    Kolkata
     Teacher                 140868     Abhishek    Male  60.0      Surat
     Travel Consultant       152518       Pranav    Male  60.0     Kalyan
     UX/UI Designer          148352        Ritik    Male  60.0     Jaipur

                            Working Professional or Student  \
Age  Profession
18.0 Content Writer                    Working Professional
     Educational Consultant            Working Professional
     Entrepreneur                      Working Professional
     Financial Analyst                 Working Professional
     Manager                           Working Professional
...                                                     ...
60.0 Sales Executive                   Working Professional
     Software Engineer                 Working Professional
     Teacher                           Working Professional
     Travel Consultant                 Working Professional
     UX/UI Designer                    Working Professional

                                         Profession  Academic Pressure  \
Age  Profession
18.0 Content Writer                  Content Writer                NaN
     Educational Consultant  Educational Consultant                NaN
     Entrepreneur                      Entrepreneur                NaN
     Financial Analyst            Financial Analyst                NaN
     Manager                                Manager                NaN
...                                             ...                ...
60.0 Sales Executive                Sales Executive                NaN
     Software Engineer            Software Engineer                NaN
     Teacher                                Teacher                NaN
     Travel Consultant            Travel Consultant                NaN
     UX/UI Designer                  UX/UI Designer                NaN

                             Work Pressure  CGPA  Study Satisfaction  \
Age  Profession
18.0 Content Writer                    1.0   NaN                 NaN
     Educational Consultant            4.0   NaN                 NaN
     Entrepreneur                      1.0   NaN                 NaN
     Financial Analyst                 3.0   NaN                 NaN
     Manager                           4.0   NaN                 NaN
...                                    ...   ...                 ...
60.0 Sales Executive                   5.0   NaN                 NaN
     Software Engineer                 1.0   NaN                 NaN
     Teacher                           3.0   NaN                 NaN
     Travel Consultant                 1.0   NaN                 NaN
     UX/UI Designer                    3.0   NaN                 NaN

                             Job Satisfaction     Sleep Duration  \
Age  Profession
18.0 Content Writer                       1.0  Less than 5 hours
     Educational Consultant               2.0  More than 8 hours
     Entrepreneur                         2.0  Less than 5 hours
     Financial Analyst                    4.0  Less than 5 hours
     Manager                              2.0          5-6 hours
...                                       ...                ...
60.0 Sales Executive                      1.0          7-8 hours
     Software Engineer                    5.0          7-8 hours
     Teacher                              1.0          5-6 hours
     Travel Consultant                    4.0          5-6 hours
     UX/UI Designer                       5.0          7-8 hours

                            Dietary Habits    Degree  \
Age  Profession
18.0 Content Writer              Unhealthy  Class 12
     Educational Consultant       Moderate  Class 12
     Entrepreneur                 Moderate  Class 12
     Financial Analyst            Moderate       MBA
     Manager                     Unhealthy  Class 12
...                                    ...       ...
60.0 Sales Executive               Healthy       MBA
     Software Engineer            Moderate       BSc
     Teacher                       Healthy        MA
     Travel Consultant            Moderate       MHM
     UX/UI Designer              Unhealthy       BSc

                            Have you ever had suicidal thoughts ?  \
Age  Profession
18.0 Content Writer                                           Yes
     Educational Consultant                                   Yes
     Entrepreneur                                             Yes
     Financial Analyst                                        Yes
     Manager                                                  Yes
...                                                           ...
60.0 Sales Executive                                          Yes
     Software Engineer                                        Yes
     Teacher                                                  Yes
     Travel Consultant                                         No
     UX/UI Designer                                            No

                             Work/Study Hours  Financial Stress  \
Age  Profession
18.0 Content Writer                      11.0               2.0
     Educational Consultant               0.0               1.0
     Entrepreneur                         0.0               5.0
     Financial Analyst                   10.0               5.0
     Manager                             10.0               4.0
...                                       ...               ...
60.0 Sales Executive                     12.0               2.0
     Software Engineer                    8.0               1.0
     Teacher                              2.0               1.0
     Travel Consultant                    8.0               5.0
     UX/UI Designer                      12.0               2.0

                            Family History of Mental Illness
Age  Profession
18.0 Content Writer                                      Yes
     Educational Consultant                              Yes
     Entrepreneur                                        Yes
     Financial Analyst                                   Yes
     Manager                                              No
...                                                      ...
60.0 Sales Executive                                      No
     Software Engineer                                   Yes
     Teacher                                             Yes
     Travel Consultant                                   Yes
     UX/UI Designer                                      Yes

[1462 rows x 19 columns]

In [8]:
# .agg() trong pandas dùng để áp dụng một hoặc nhiều hàm thống kê/tổng hợp (aggregation functions) 
# lên từng nhóm dữ liệu sau khi đã groupby
df.groupby(['City']).Age.agg([len, min, max])

C:\Users\hoang\AppData\Local\Temp\ipykernel_10164\131338484.py:3: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['City']).Age.agg([len, min, max])
C:\Users\hoang\AppData\Local\Temp\ipykernel_10164\131338484.py:3: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['City']).Age.agg([len, min, max])

                len   min   max
City
Abhinav           1  23.0  23.0
Aditi             1  23.0  23.0
Agra           3189  18.0  60.0
Ahmedabad      3677  18.0  60.0
Avni              1  47.0  47.0
...             ...   ...   ...
Vasai-Virar    3897  18.0  60.0
Vidhi             1  59.0  59.0
Vidya             4  30.0  52.0
Vikram            2  24.0  32.0
Visakhapatnam  3416  18.0  60.0

[68 rows x 3 columns]

### 2. Multi Indexces

In [9]:
city_reviewed = df.groupby(['City', 'Profession']).Degree.agg([len])
city_reviewed

                                 len
City          Profession
Aditi         Consultant           1
Agra          3M                   1
              Accountant          24
              Architect           97
              Business Analyst    92
...                              ...
Visakhapatnam Software Engineer   27
              Student              1
              Teacher            633
              Travel Consultant   27
              UX/UI Designer      26

[1128 rows x 1 columns]

In [10]:
mi = city_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [11]:
city_reviewed.reset_index() # chuyển index thành cột

               City         Profession  len
0             Aditi         Consultant    1
1              Agra                 3M    1
2              Agra         Accountant   24
3              Agra          Architect   97
4              Agra   Business Analyst   92
...             ...                ...  ...
1123  Visakhapatnam  Software Engineer   27
1124  Visakhapatnam            Student    1
1125  Visakhapatnam            Teacher  633
1126  Visakhapatnam  Travel Consultant   27
1127  Visakhapatnam     UX/UI Designer   26

[1128 rows x 3 columns]

### 3. Sorting

In [12]:
city_reviewed

                                 len
City          Profession
Aditi         Consultant           1
Agra          3M                   1
              Accountant          24
              Architect           97
              Business Analyst    92
...                              ...
Visakhapatnam Software Engineer   27
              Student              1
              Teacher            633
              Travel Consultant   27
              UX/UI Designer      26

[1128 rows x 1 columns]

In [13]:
city_reviewed.sort_values(by='len')

                          len
City          Profession
Aditi         Consultant    1
Agra          3M            1
Visakhapatnam Student       1
Agra          PhD           1
Vidya         Architect     1
...                       ...
Kalyan        Teacher     726
Vadodara      Teacher     731
Srinagar      Teacher     756
Patna         Teacher     779
Ahmedabad     Teacher     804

[1128 rows x 1 columns]

In [14]:
city_reviewed.sort_index()

                                 len
City          Profession
Aditi         Consultant           1
Agra          3M                   1
              Accountant          24
              Architect           97
              Business Analyst    92
...                              ...
Visakhapatnam Software Engineer   27
              Student              1
              Teacher            633
              Travel Consultant   27
              UX/UI Designer      26

[1128 rows x 1 columns]

In [15]:
city_reviewed.sort_values(by=['City', 'Profession'])

                                 len
City          Profession
Aditi         Consultant           1
Agra          3M                   1
              Accountant          24
              Architect           97
              Business Analyst    92
...                              ...
Visakhapatnam Software Engineer   27
              Student              1
              Teacher            633
              Travel Consultant   27
              UX/UI Designer      26

[1128 rows x 1 columns]

### Pivot table : một method thay cho groupby để tính toán các giá trị nhóm

In [16]:
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [24]:
df.pivot_table(values="Work Pressure",
               index="id",
               aggfunc=["median", "mean"],
               margins=True) # margins=True để tính tổng cho các cột và hàng

              median          mean
       Work Pressure Work Pressure
id
140700           2.0      2.000000
140701           2.0      2.000000
140702           4.0      4.000000
140704           5.0      5.000000
140705           2.0      2.000000
...              ...           ...
234495           3.0      3.000000
234496           5.0      5.000000
234498           4.0      4.000000
234499           5.0      5.000000
All              3.0      3.011797

[75023 rows x 2 columns]