In [1]:
import pandas as pd

In [2]:
# Read csv file
df = pd.read_csv('../test.csv')
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

### Manipulating the index

In [3]:
df.set_index("id") # Chọn index là id

,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
id,,,,,,,,,,,,,,,,,,
140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234495,Zoya,Female,49.0,Jaipur,Working Professional,Pilot,NaN,3.0,NaN,NaN,5.0,Less than 5 hours,Moderate,BSc,Yes,2.0,2.0,Yes
234496,Shlok,Male,29.0,Ahmedabad,Working Professional,Pilot,NaN,5.0,NaN,NaN,1.0,7-8 hours,Moderate,BE,Yes,11.0,3.0,Yes
234497,Rishi,Male,24.0,Visakhapatnam,Student,NaN,1.0,NaN,7.51,4.0,NaN,7-8 hours,Moderate,B.Tech,No,7.0,1.0,No
234498,Eshita,Female,23.0,Kalyan,Working Professional,Marketing Manager,NaN,4.0,NaN,NaN,2.0,5-6 hours,Healthy,BA,Yes,7.0,5.0,Yes
234499,Gauri,Female,43.0,Varanasi,Working Professional,Educational Consultant,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,B.Ed,No,11.0,2.0,No

### Conditional selection

In [4]:
df['Work/Study Hours'] == 0.0

0        False
1        False
2        False
3        False
4        False
         ...
93795    False
93796    False
93797    False
93798    False
93799    False
Name: Work/Study Hours, Length: 93800, dtype: bool

In [5]:
df.loc[df['Work/Study Hours'] == 0.0, "Work/Study Hours"]

7        0.0
13       0.0
30       0.0
33       0.0
36       0.0
        ...
93727    0.0
93729    0.0
93733    0.0
93763    0.0
93779    0.0
Name: Work/Study Hours, Length: 8132, dtype: float64

In [6]:
df.loc[(df['Work/Study Hours'] == 0.0) & (df.Age <= 30) & (df['Dietary Habits'] != 'Healthy')]

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
13,140713,Reyansh,Male,18.0,Visakhapatnam,Working Professional,NaN,NaN,5.0,NaN,NaN,2.0,5-6 hours,Moderate,Class 12,Yes,0.0,2.0,No
74,140774,Krishna,Male,18.0,Delhi,Working Professional,NaN,NaN,3.0,NaN,NaN,1.0,7-8 hours,Unhealthy,Class 12,No,0.0,3.0,No
133,140833,Tanisha,Female,20.0,Srinagar,Student,NaN,5.0,NaN,7.94,4.0,NaN,7-8 hours,Moderate,Class 12,Yes,0.0,3.0,Yes
153,140853,Yogesh,Male,24.0,Jaipur,Working Professional,Architect,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,B.Arch,No,0.0,1.0,No
313,141013,Dhruv,Male,23.0,Kolkata,Working Professional,Chemist,NaN,1.0,NaN,NaN,1.0,7-8 hours,Unhealthy,B.Pharm,Yes,0.0,4.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92932,233632,Aariv,Male,25.0,Rajkot,Working Professional,Plumber,NaN,1.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,PhD,No,0.0,1.0,Yes
93154,233854,Tushar,Male,20.0,Thane,Working Professional,NaN,NaN,3.0,NaN,NaN,5.0,5-6 hours,Unhealthy,Class 12,No,0.0,3.0,No
93370,234070,Raunak,Male,26.0,Surat,Working Professional,Customer Support,NaN,1.0,NaN,NaN,3.0,7-8 hours,Unhealthy,MA,No,0.0,1.0,Yes
93385,234085,Raghavendra,Male,24.0,Bangalore,Working Professional,Sales Executive,NaN,2.0,NaN,NaN,5.0,5-6 hours,Moderate,BBA,Yes,0.0,2.0,Yes
93558,234258,Leela,Female,27.0,Lucknow,Student,NaN,4.0,NaN,7.77,1.0,NaN,5-6 hours,Moderate,B.Com,Yes,0.0,4.0,No

In [7]:
# .isin() chọn dữ liệu có giá trị "nằm trong" một danh sách các giá trị.
df.loc[df.City.isin(['Rajkot', 'Kolkata'])]

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
50,140750,Aanchal,Female,53.0,Kolkata,Working Professional,Pharmacist,NaN,2.0,NaN,NaN,3.0,More than 8 hours,Moderate,MBBS,Yes,1.0,4.0,No
86,140786,Naina,Female,57.0,Kolkata,Working Professional,Travel Consultant,NaN,3.0,NaN,NaN,4.0,5-6 hours,Moderate,BHM,Yes,1.0,1.0,No
89,140789,Ishaani,Female,57.0,Rajkot,Working Professional,Teacher,NaN,4.0,NaN,NaN,2.0,7-8 hours,Moderate,B.Ed,No,0.0,3.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93752,234452,Prisha,Female,29.0,Kolkata,Working Professional,Financial Analyst,NaN,2.0,NaN,NaN,1.0,Less than 5 hours,Moderate,M.Com,No,8.0,5.0,Yes
93758,234458,Aarav,Male,58.0,Rajkot,Working Professional,Consultant,NaN,2.0,NaN,NaN,2.0,More than 8 hours,Moderate,MCA,Yes,12.0,3.0,Yes
93765,234465,Rahil,Male,48.0,Rajkot,Working Professional,HR Manager,NaN,4.0,NaN,NaN,2.0,7-8 hours,Healthy,BBA,Yes,10.0,5.0,No
93781,234481,Aarohi,Female,49.0,Kolkata,Working Professional,Teacher,NaN,1.0,NaN,NaN,3.0,7-8 hours,Healthy,B.Arch,No,12.0,3.0,No
93788,234488,Rahil,Male,40.0,Kolkata,Working Professional,Chemist,NaN,4.0,NaN,NaN,5.0,More than 8 hours,Moderate,M.Pharm,Yes,10.0,3.0,No

In [ ]:
# isnull và notnull
df.loc[df['Academic Pressure'].notnull()]

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
8,140708,Navya,Female,21.0,Surat,Student,NaN,1.0,NaN,7.39,3.0,NaN,Less than 5 hours,Healthy,BBA,No,8.0,1.0,Yes
19,140719,Kiran,Male,28.0,Lucknow,Student,NaN,5.0,NaN,6.03,3.0,NaN,7-8 hours,Moderate,MA,No,11.0,3.0,Yes
20,140720,Rashi,Female,26.0,Ghaziabad,Student,NaN,3.0,NaN,8.63,5.0,NaN,More than 8 hours,Moderate,BBA,Yes,10.0,4.0,Yes
21,140721,Manan,Male,32.0,Visakhapatnam,Student,NaN,3.0,NaN,8.61,1.0,NaN,Less than 5 hours,Moderate,M.Ed,Yes,11.0,5.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93785,234485,Ishaan,Male,33.0,Agra,Student,NaN,5.0,NaN,5.74,2.0,NaN,7-8 hours,Moderate,B.Com,Yes,12.0,5.0,Yes
93790,234490,Abhishek,Male,19.0,Nashik,Student,NaN,4.0,NaN,8.96,3.0,NaN,7-8 hours,Unhealthy,Class 12,No,2.0,2.0,Yes
93793,234493,Aohi,Female,29.0,Vadodara,Student,NaN,2.0,NaN,5.58,5.0,NaN,More than 8 hours,Healthy,Class 12,Yes,8.0,2.0,Yes
93794,234494,Shlok,Male,33.0,Nashik,Student,NaN,1.0,NaN,7.92,2.0,NaN,More than 8 hours,Healthy,BA,Yes,9.0,2.0,No
93797,234497,Rishi,Male,24.0,Visakhapatnam,Student,NaN,1.0,NaN,7.51,4.0,NaN,7-8 hours,Moderate,B.Tech,No,7.0,1.0,No