In [4]:
import pandas as pd
pokemon = pd.read_csv("../pokemon.csv")

In [6]:
pokemon.columns

Index(['No', 'Name', 'Type 1', 'Type 2', 'Height', 'Weight', 'Legendary'], dtype='object')

In [8]:
pokemon.index

RangeIndex(start=0, stop=150, step=1)

# Setting a column as the index

In [11]:
pokemon_ind = pokemon.set_index("Name")
pokemon_ind

             No   Type 1  Type 2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

# Removing a index

In [10]:
pokemon_ind.reset_index()

           Name   No   Type 1  Type 2  Height  Weight  Legendary
0     Bulbasaur    1    Grass  Poison     0.7     6.9          0
1       Ivysaur    2    Grass  Poison     1.0    13.0          0
2      Venusaur    3    Grass  Poison     2.0   100.0          0
3    Charmander    4     Fire     NaN     0.6     8.5          0
4    Charmeleon    5     Fire     NaN     1.1    19.0          0
..          ...  ...      ...     ...     ...     ...        ...
145     Moltres  146     Fire  Flying     2.0    60.0          1
146     Dratini  147   Dragon     NaN     1.8     3.3          0
147   Dragonair  148   Dragon     NaN     4.0    16.5          0
148   Dragonite  149   Dragon  Flying     2.2   210.0          0
149      Mewtwo  150  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

# Droppin an index

In [12]:
pokemon_ind.reset_index(drop=True)

      No   Type 1  Type 2  Height  Weight  Legendary
0      1    Grass  Poison     0.7     6.9          0
1      2    Grass  Poison     1.0    13.0          0
2      3    Grass  Poison     2.0   100.0          0
3      4     Fire     NaN     0.6     8.5          0
4      5     Fire     NaN     1.1    19.0          0
..   ...      ...     ...     ...     ...        ...
145  146     Fire  Flying     2.0    60.0          1
146  147   Dragon     NaN     1.8     3.3          0
147  148   Dragon     NaN     4.0    16.5          0
148  149   Dragon  Flying     2.2   210.0          0
149  150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

# Make subsetting simpler

In [15]:
pokemon[pokemon["Name"].isin(["Pikachu", "Bulbasaur"])] # isin là phương thức để kiểm tra xem các giá trị trong một cột có nằm trong một danh sách cụ thể hay không

    No       Name    Type 1  Type 2  Height  Weight  Legendary
0    1  Bulbasaur     Grass  Poison     0.7     6.9          0
24  25    Pikachu  Electric     NaN     0.4     6.0          0

In [ ]:
pokemon.sort_index()