In [1]:
import pandas as pd

In [5]:
# Reading csv file
df = pd.read_csv("../test.csv")
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

### 1. Index-based selection (Chọn dựa trên chỉ số): iloc[row, col]

```iloc[row, col]``` : row và col là index trong dataframe

In [ ]:
# Select first row of dataframe
df.iloc[0] # iloc và loc giống nhau về syntax: [row, column] nhưng cách dùng khác nhau

id                                                     140700
Name                                                   Shivam
Gender                                                   Male
Age                                                      53.0
City                                            Visakhapatnam
Working Professional or Student          Working Professional
Profession                                              Judge
Academic Pressure                                         NaN
Work Pressure                                             2.0
CGPA                                                      NaN
Study Satisfaction                                        NaN
Job Satisfaction                                          5.0
Sleep Duration                              Less than 5 hours
Dietary Habits                                       Moderate
Degree                                                    LLB
Have you ever had suicidal thoughts ?                      No
Work/Study Hours                                          9.0
Financial Stress                                          3.0
Family History of Mental Illness                          Yes
Name: 0, dtype: object

In [29]:
# Get a column of dataframe
df.iloc[:, 3] # lấy column đầu. Dấu : là lấy đến n row trong dataframe

0        53.0
1        58.0
2        53.0
3        23.0
4        47.0
         ...
93795    49.0
93796    29.0
93797    24.0
93798    23.0
93799    43.0
Name: Age, Length: 93800, dtype: float64

In [30]:
df.iloc[:3, :2]

       id    Name
0  140700  Shivam
1  140701   Sanya
2  140702    Yash

In [ ]:
df.iloc[[0,1,2], 0] # = df.iloc[:3,0]

0    140700
1    140701
2    140702
Name: id, dtype: int64

In [22]:
# Select just second and third entries
df.iloc[1:3, 0]

1    140701
2    140702
Name: id, dtype: int64

In [ ]:
df.iloc[-5:] # số âm thì lấy từ cuối data đi lên

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
93795,234495,Zoya,Female,49.0,Jaipur,Working Professional,Pilot,NaN,3.0,NaN,NaN,5.0,Less than 5 hours,Moderate,BSc,Yes,2.0,2.0,Yes
93796,234496,Shlok,Male,29.0,Ahmedabad,Working Professional,Pilot,NaN,5.0,NaN,NaN,1.0,7-8 hours,Moderate,BE,Yes,11.0,3.0,Yes
93797,234497,Rishi,Male,24.0,Visakhapatnam,Student,NaN,1.0,NaN,7.51,4.0,NaN,7-8 hours,Moderate,B.Tech,No,7.0,1.0,No
93798,234498,Eshita,Female,23.0,Kalyan,Working Professional,Marketing Manager,NaN,4.0,NaN,NaN,2.0,5-6 hours,Healthy,BA,Yes,7.0,5.0,Yes
93799,234499,Gauri,Female,43.0,Varanasi,Working Professional,Educational Consultant,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,B.Ed,No,11.0,2.0,No

### 2. Label-based selection (Chọn dựa trên nhãn): loc[row, col]

```loc[row, col]``` : row là index nhưng col là data index value (VD: Gender)

In [ ]:
# Get the first entry
df.loc[0, 'Gender']

'Male'

In [26]:
df.loc[:, ['Name', 'Gender', 'Age']]

          Name  Gender   Age
0       Shivam    Male  53.0
1        Sanya  Female  58.0
2         Yash    Male  53.0
3       Nalini  Female  23.0
4      Shaurya    Male  47.0
...        ...     ...   ...
93795     Zoya  Female  49.0
93796    Shlok    Male  29.0
93797    Rishi    Male  24.0
93798   Eshita  Female  23.0
93799    Gauri  Female  43.0

[93800 rows x 3 columns]