In [1]:
import pandas as pd

In [2]:
# Reading csv file
df = pd.read_csv("../test.csv")
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

### 1. Selecting one Column

#### 1.1 Syntax 1

In [3]:
# Selecting a column with [] (prefered way to select a column)
df["Gender"]

0          Male
1        Female
2          Male
3        Female
4          Male
          ...
93795    Female
93796      Male
93797      Male
93798    Female
93799    Female
Name: Gender, Length: 93800, dtype: object

In [4]:
# Check out a data type of a column
type(df["Gender"])

pandas.core.series.Series

In [5]:
# Series: attributes and methods
df['Gender'].index
df['Gender'].head()

0      Male
1    Female
2      Male
3    Female
4      Male
Name: Gender, dtype: object

#### 1.1 Syntax 2

In [6]:
# Selecting a column with .
df.Gender

0          Male
1        Female
2          Male
3        Female
4          Male
          ...
93795    Female
93796      Male
93797      Male
93798    Female
93799    Female
Name: Gender, Length: 93800, dtype: object

In [7]:
# Selecting a column with . (pitfalls)
# df.Work Pressure # -> ERROR

In [8]:
# Selecting the same column using []
df['Work Pressure']

0        2.0
1        2.0
2        4.0
3        NaN
4        5.0
        ...
93795    3.0
93796    5.0
93797    NaN
93798    4.0
93799    5.0
Name: Work Pressure, Length: 93800, dtype: float64

### 2. Selecting two or MORE column

In [9]:
# Select 2 columns using [[]]
df[['Gender', 'Work Pressure']] # theo order đặt: Gender trước, Work Pressure sau

       Gender  Work Pressure
0        Male            2.0
1      Female            2.0
2        Male            4.0
3      Female            NaN
4        Male            5.0
...       ...            ...
93795  Female            3.0
93796    Male            5.0
93797    Male            NaN
93798  Female            4.0
93799  Female            5.0

[93800 rows x 2 columns]

In [10]:
# Check out the data type of selection
type(df[['Gender', 'Work Pressure']]) 
# => Khi dùng [[]] ta sẽ nhận về 1 DataFrame, còn [] thì nhận về Series (mảng một chiều)

pandas.core.frame.DataFrame

In [11]:
# Select 2 or more columns using [[]]
df[['Gender', 'Work Pressure', 'CGPA', 'Study Satisfaction','Job Satisfaction']]

       Gender  Work Pressure  CGPA  Study Satisfaction  Job Satisfaction
0        Male            2.0   NaN                 NaN               5.0
1      Female            2.0   NaN                 NaN               4.0
2        Male            4.0   NaN                 NaN               1.0
3      Female            NaN  6.84                 1.0               NaN
4        Male            5.0   NaN                 NaN               5.0
...       ...            ...   ...                 ...               ...
93795  Female            3.0   NaN                 NaN               5.0
93796    Male            5.0   NaN                 NaN               1.0
93797    Male            NaN  7.51                 4.0               NaN
93798  Female            4.0   NaN                 NaN               2.0
93799  Female            5.0   NaN                 NaN               2.0

[93800 rows x 5 columns]

In [12]:
# TODO: Cannot select 2 or more columns with the "."